---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах  
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - При регистрации пользователь должен оставить контактные данные, чтобы можно было оформить заказ
  - Пользователь должен иметь возможность удалять все количество товара из корзины одним действием
  - Значок Корзины должен показывать количество добавленных товаров, а не общую сумму единиц товаров в корзине
  - Значок Hexlet Store должен перенаправлять на главную страницу сайта
  - При переключении языка сайта, весь текст на сайте должен быть отображен в соответсвии с выбранным языком
